sidebar_width:
  type: integer
  default: 17
  description: Change this in case of custom sidebar width. Value in EM only.
svg_icons:
  default: 'expand|compress'
  type: 'list'
  list_type: 'compact'